### ISSUE TITLE
mtllib directive with material file names containing spaces gets split and fails to load

### ISSUE THREAD

**Issue by Aar0n2103** [tinyobjloader/tinyobjloader#385] opened 2024-09-11 15:33 UTC
**Describe the issue**
When attempting to load an .obj file that references a material file via the mtllib directive, if the material file name contains a space, TinyObjLoader incorrectly splits the file name and fails to load the material. This results in the material file not being recognized, which causes missing or incorrectly rendered materials in the scene. When testing these files in other .obj viewers, the materials are loaded correctly without issue, suggesting that the space in the material file name should be supported.

**To Reproduce**
1. Load .obj file 'colored cubes.obj'
2. See that there are no materials so the cubes are not colored

Please attach minimal and reproducible files(source codes, .obj/.mtl files, etc)
[colored cubes.zip](https://github.com/user-attachments/files/16965940/colored.cubes.zip)

**Expected behavior**
The loader should correctly handle spaces in the material file name, allowing the material to be loaded and applied without splitting the file name at the space.

**Environment**
 - TinyObjLoader version: release branch
 - OS: [Windows]
 - Compiler  [MSVC]

**Comment by syoyo** [comment] 2024-09-11 15:41
Duplicate of https://github.com/tinyobjloader/tinyobjloader/issues/49

**Closed** 2024-09-11 15:42 UTC
Labels: invalid
