### ISSUE TITLE
Render Bug ?

### ISSUE THREAD

**Issue by RedzikGit** [tinyobjloader/tinyobjloader#326] opened 2021-12-16 19:41 UTC
Hi,

In short bad render

![image](https://user-images.githubusercontent.com/25783409/146436522-71e50b7d-171a-48d5-bf90-f70ba805cf93.png)

inside view 
![image](https://user-images.githubusercontent.com/25783409/146437194-7b5680b2-8d2a-48e0-a857-93be1c96044c.png)

Environment:
 - TinyObjLoader **v2.0 release candidate1**
 - OS: **Windows 10 x64**
 - Compiler  **gcc version 10.3.0 (tdm64-1) C20**

**MODEL:**
```

# WaveFront *.obj file (generated by Cinema 4D)

mtllib ./casa.mtl

v 2.794960 3.727999 0.115395
v 2.786309 3.509150 0.115247
v 3.089318 3.834272 0.117251
v 3.119978 3.620358 0.118524
v 2.796539 3.728110 -0.141715
v 2.787888 3.509261 -0.141862
v 3.090897 3.834382 -0.139858
v 3.121557 3.620469 -0.138586
v 2.417797 3.681780 0.113058
v 2.409146 3.462931 0.112911
v 2.410725 3.463041 -0.144199
v 2.419376 3.681890 -0.144051
v 2.150582 3.677794 0.111415
v 2.141931 3.458945 0.111268
v 2.143510 3.459055 -0.145841
v 2.152161 3.677904 -0.145694
v 1.781926 3.725499 0.109172
v 1.773275 3.506650 0.109024
v 1.774854 3.506761 -0.148085
v 1.783505 3.725610 -0.147938
v 1.581490 3.794389 0.106010
v 1.503508 3.599326 0.099764
v 1.521200 3.597199 -0.156472
v 1.599183 3.792263 -0.150227
v 3.242101 3.679251 0.119316
v 3.192404 3.884715 0.117880
v 3.192819 3.884551 -0.139233
v 3.242515 3.679088 -0.137797
v 1.356514 3.902486 0.104782
v 1.278532 3.707422 0.098536
v 1.296224 3.705296 -0.157700
v 1.374207 3.900360 -0.151455
v 2.607530 3.694187 -0.142885
v 2.605951 3.694076 0.114225
v 2.597300 3.475227 0.114077
v 2.598879 3.475338 -0.143032
v 2.944307 3.772727 0.116373
v 2.955312 3.556346 0.116936
v 2.945886 3.772838 -0.140736
v 2.956891 3.556456 -0.140174
v 1.977576 3.689579 -0.146761
v 1.975997 3.689469 0.110348
v 1.967346 3.470620 0.110201
v 1.968925 3.470730 -0.146909
v 3.192542 3.884660 0.031896
v 3.191668 3.863191 0.047841
v 3.192476 3.884686 0.072724
v 3.209547 3.814154 0.066231
v 3.123321 3.850756 0.057228
v 2.249893 3.679339 -0.077396
v 2.268426 3.636026 -0.144998
v 2.268426 3.636026 -0.144998
v 1.708474 3.750745 0.108013
v 1.772269 3.728819 0.109019
v 1.744262 3.739135 0.063808
v 1.737879 3.635350 0.108472
v 1.737879 3.635350 0.108472
# 57 vertices

vn -0.009281 0.003375 0.999937
vn 0.008687 -0.004781 -0.999937
vn 0.008594 -0.000875 -0.999937
vn -0.065187 0.997844 0.000000
vn -0.286875 0.957937 -0.001375
vn 0.268969 -0.963125 0.001187
vn 0.014875 -0.999875 -0.000281
vn 0.065187 -0.997844 0.000000
vn 0.006187 0.000375 -0.999969
vn -0.006187 -0.000375 0.999969
vn 0.182500 0.983187 0.001500
vn -0.006094 -0.000375 0.999969
vn -0.329875 -0.943969 -0.008687
vn -0.182500 -0.983187 -0.001500
vn 0.006094 0.000375 -0.999969
vn 0.432875 0.901156 0.022375
vn 0.027781 0.009594 -0.999563
vn 0.435187 -0.900312 0.001781
vn -0.008594 0.004781 0.999937
vn -0.925719 0.372187 -0.067000
vn -0.017500 -0.025000 0.999531
vn -0.432875 -0.901156 -0.022375
vn 0.017500 0.025000 -0.999531
vn 0.176687 -0.984250 0.000687
vn -0.176687 0.984250 -0.000687
vn 0.362281 -0.932063 0.001781
vn -0.390687 0.920500 -0.002000
vn 0.009281 -0.003375 -0.999937
vn -0.008594 0.000875 0.999937
vn -0.066688 -0.997750 -0.000781
vn 0.066688 0.997750 0.000781
vn 0.936688 0.249281 -0.245781
vn 0.595375 0.463281 0.656375
vn 0.001781 0.596187 0.802813
vn -0.221875 0.741406 -0.633281
vn 0.000000 0.000000 1.000000
vn 0.235687 -0.787594 0.569281
vn 0.304469 0.837750 -0.453250
vn 0.786375 0.202688 0.583500
vn -0.784281 0.285281 0.550875
vn -0.014875 0.999875 0.000281
vn 0.332375 0.943094 0.008594
vn -0.030469 -0.009875 0.999469
vn 0.971969 0.235062 0.001375
vn -0.440594 0.897687 -0.001781
# 45 normals

vt 0.375000 0.250000 0.000000
vt 0.625000 0.250000 0.000000
vt 0.625000 0.125000 0.000000
vt 0.375000 0.125000 0.000000
vt 0.625000 0.500000 0.000000
vt 0.375000 0.500000 0.000000
vt 0.375000 0.750000 0.000000
vt 0.625000 0.750000 0.000000
vt 0.625000 0.625000 0.000000
vt 0.375000 0.625000 0.000000
vt 0.125000 0.750000 0.000000
vt 0.125000 0.625000 0.000000
vt 0.875000 0.750000 0.000000
vt 0.875000 0.625000 0.000000
vt 0.625000 0.000000 0.000000
vt 0.375000 0.000000 0.000000
vt 0.875000 0.500000 0.000000
vt 0.375000 1.000000 0.000000
vt 0.625000 1.000000 0.000000
vt 0.125000 0.500000 0.000000
vt 0.375000 0.318088 0.000000
vt 0.460815 0.300700 0.000000
vt 0.375000 0.293907 0.000000
vt 0.375000 0.333606 0.000000
vt 0.193088 0.500000 0.000000
vt 0.183564 0.500000 0.000000
vt 0.208606 0.500000 0.000000
vt 0.168907 0.500000 0.000000
vt 0.424849 0.750000 0.000000
vt 0.309177 0.750000 0.000000
vt 0.168556 0.750000 0.000000
vt 0.493642 0.000000 0.000000
# 32 texture coordinates

o Cubo.004
usemtl madera
f 37/4/1 38/3/1 4/2/1 3/1/1
f 8/5/2 7/6/2 27/6/2 28/5/2
f 39/10/3 40/9/3 6/8/3 5/7/3
f 34/11/4 33/7/4 12/7/4 9/11/4
f 37/12/5 39/10/5 5/7/5 1/11/5
f 40/9/6 38/14/6 2/13/6 6/8/6
f 11/8/7 10/13/7 14/13/7 15/8/7
f 36/8/8 35/13/8 10/13/8 11/8/8
f 33/7/9 36/8/9 11/8/9 12/7/9
f 35/15/10 34/16/10 9/16/10 10/15/10
f 42/11/11 41/7/11 20/7/11 17/11/11
f 10/15/12 9/16/12 13/16/12 14/15/12
f 19/8/13 18/13/13 22/13/13 23/8/13
f 43/15/12 42/16/12 17/16/12 18/15/12
f 44/8/14 43/13/14 18/13/14 19/8/14
f 41/7/15 44/8/15 19/8/15 20/7/15
f 21/11/16 24/7/16 32/7/16 29/11/16
f 20/7/17 19/8/17 23/8/17 24/7/17
f 4/17/18 8/5/18 28/5/18 25/17/18
f 3/1/19 4/2/19 25/2/19 26/1/19
f 32/7/20 31/8/20 30/19/20 29/18/20
f 22/15/21 21/16/21 29/16/21 30/15/21
f 23/8/22 22/13/22 30/13/22 31/8/22
f 24/7/23 23/8/23 31/8/23 32/7/23
f 2/15/12 1/16/12 34/16/12 35/15/12
f 5/7/15 6/8/15 36/8/15 33/7/15
f 6/8/24 2/13/24 35/13/24 36/8/24
f 1/11/25 5/7/25 33/7/25 34/11/25
f 8/5/26 4/17/26 38/14/26 40/9/26
f 3/20/27 7/6/27 39/10/27 37/12/27
f 7/6/28 8/5/28 40/9/28 39/10/28
f 1/16/29 2/15/29 38/3/29 37/4/29
f 16/7/15 15/8/15 44/8/15 41/7/15
f 15/8/30 14/13/30 43/13/30 44/8/30
f 14/15/12 13/16/12 42/16/12 43/15/12
f 13/11/31 16/7/31 41/7/31 42/11/31
f 47/23/32 48/22/32 46/21/32
f 46/21/33 48/22/33 45/24/33
f 45/27/34 49/26/34 46/25/34
f 46/25/35 49/26/35 47/28/35
f 52/29/36 51/29/36 12/7/36
f 52/29/37 12/7/37 50/30/37
f 16/7/38 50/30/38 52/29/38
f 56/32/39 55/31/39 53/16/39
f 57/32/40 54/11/40 55/31/40 56/32/40
f 12/7/15 11/8/15 15/8/15 16/7/15 52/29/15
f 9/11/41 12/7/41 50/30/41 16/7/41 13/11/41
f 17/11/42 20/7/42 24/7/42 21/11/42 53/11/42 55/31/42 54/11/42
f 18/15/43 17/16/43 54/16/43 57/32/43 56/32/43 53/16/43 21/16/43 22/15/43
f 26/1/44 25/2/44 28/5/44 27/6/44 45/24/44 48/22/44 47/23/44
f 7/6/45 3/20/45 26/20/45 47/28/45 49/26/45 45/27/45 27/6/45
```

**Comment by syoyo** [comment] 2021-12-17 08:18
![Screenshot from 2021-12-17 17-11-40](https://user-images.githubusercontent.com/18676/146512068-2d59ebb9-5160-42fb-8c60-8f61a2c7ef52.png)

When viewing the mesh in Blender, some faces are already flipped so the issue is model itself or C4D exporter.
 
![Screenshot from 2021-12-17 17-15-27](https://user-images.githubusercontent.com/18676/146512072-68045c4b-da87-413f-bb1d-e6efef534351.png)

There is another issue that tinyobjloader's built-in triangulation does not work well for some faces(generates `cracks`), which will be fixed in https://github.com/tinyobjloader/tinyobjloader/issues/319

**Closed by syoyo** 2021-12-17 08:18 UTC
