### ISSUE TITLE
Faces normal reverse after triangulation ？

### ISSUE THREAD

**Issue by wongshek** [tinyobjloader/tinyobjloader#319] opened 2021-09-14 08:51 UTC
**Describe the issue**
Import a polygon .obj file with triangulation (earcut option on), then export to .off, but some face normal reverse.

**To Reproduce**
- Minimal files
[ZH2.obj](https://github.com/wsh2021/FILE/blob/main/ZH2.obj)
[ZH2.mtl](https://github.com/wsh2021/FILE/blob/main/ZH2.mtl)

- Code:
```c++
/*********************Read Mesh*******************/
std::string inputfile = meshName;
tinyobj::ObjReaderConfig reader_config;
reader_config.triangulate = true;
reader_config.triangulation_method = "earcut";
reader_config.vertex_color = false;
reader_config.mtl_search_path = "./";

tinyobj::ObjReader reader;

if (!reader.ParseFromFile(inputfile, reader_config)) {
	if (!reader.Error().empty()) {
		std::cerr << "TinyObjReader: " << reader.Error();
	}
	exit(1);
}

auto& attrib = reader.GetAttrib();
auto& shapes = reader.GetShapes();
auto& materials = reader.GetMaterials();

// Loop over vertices
for (size_t i = 0; i < attrib.vertices.size(); i += 3)
{
	Point3d XYZ;
	XYZ.x = attrib.vertices[i + 0];
	XYZ.y = attrib.vertices[i + 1];
	XYZ.z = attrib.vertices[i + 2];
	vertexdPosition.emplace_back(XYZ);
}

// Loop over shapes
for (size_t s = 0; s < shapes.size(); s++)
{
	// Loop over faces(triangle)
	for (size_t f = 0; f < shapes[s].mesh.num_face_vertices.size(); f++)
	{
		// Access to vertex
		int id_x = shapes[s].mesh.indices[3 * f + 0].vertex_index;
		int id_y = shapes[s].mesh.indices[3 * f + 1].vertex_index;
		int id_z = shapes[s].mesh.indices[3 * f + 2].vertex_index;

		Point3i index;
		index.x = id_x;
		index.y = id_y;
		index.z = id_z;

		triangleIndex.emplace_back(index);
	}
}

/*********************Write Mesh*******************/
std::ofstream outFile("mesh.off");
outFile << "OFF" << std::endl;
outFile << vertexdPosition.size() << " "
		<< triangleIndex.size() << " " << 0 << std::endl;
for (const auto& pos : vertexdPosition)
{
	outFile << pos.x << " " << pos.y << " " << pos.z << std::endl;
}
outFile << std::endl;
for (const auto& idx : triangleIndex)
{
	outFile << 3 << " " << idx.x << " " << idx.y << " " << idx.z << std::endl;
}
outFile.close();
```
- Result:
![image](https://user-images.githubusercontent.com/87893723/133225027-436424fe-daea-4290-891f-7f2973a55949.png)

**Expected behavior**
Face without reverse.

**Environment**
 - TinyObjLoader version 2.0.0
 - OS: [windows 10]

**Comment by syoyo** [comment] 2021-09-14 09:58
@wsh2021 Thanks!

According to earcut's document, mapbox earcut produces triangles in clockwise

> Three subsequent indices form a triangle. Output triangles are clockwise

https://github.com/mapbox/earcut.hpp/blob/master/README.md

Whereas tinyobjloader uses counter-clockwise order, so there are face inversions.

I made a fix. Please try this(at least I've confirmed face flipping has been fixed in my local test)

https://github.com/tinyobjloader/tinyobjloader/pull/320

**Comment by wsh2021** [comment] 2021-09-14 12:02
@syoyo 

Thanks for the quick response!

I have tried the modified code, however there are still some bugs, I suspect there are some deeper reasons.

See these files(I didn't delete unnecessary vertices):
[ZH2_big.obj](https://github.com/wsh2021/FILE/blob/main/ZH2_big.obj)
[ZH2_big.mtl](https://github.com/wsh2021/FILE/blob/main/ZH2_big.mtl)
[ZH2_result.off](https://github.com/wsh2021/FILE/blob/main/ZH2_result.off)

![image](https://user-images.githubusercontent.com/87893723/133253899-7471b3a6-031e-49b7-9fb1-27ed205fe4ba.png)

**Comment by syoyo** [comment] 2021-09-14 12:17
Hmm... we may need to consider vertex order(plane normal) of input .obj polygon.

Although robust normal detection may not be possible or difficult for non-planar surface, at least it should work well for ZH2_big data(faces are mostly planar)

**Comment by wsh2021** [comment] 2021-09-14 12:21
I didn't fully understand the code. But if earcut is assumed to be correct, is it possible that there are some problems when turning 3D points to 2D?

**Comment by wsh2021** [comment] 2021-09-14 12:32
Can we cross multiply two adjacent **convex** edges(CCW order) to determine the normal vector?

**Comment by wsh2021** [comment] 2021-09-15 03:33
I suppose robust normal detection method like Newell's method is adequate to almost-planar and non-convex surface, So is the problem caused by messing up the order when converting points from 3D to 2D?

**Comment by syoyo** [comment] 2021-09-15 08:38
@wsh2021 Axis selection for 3D -> 2D conversion is done in here: https://github.com/tinyobjloader/tinyobjloader/blob/3e401b55a4a9ebfc6344a8a2a698245e7d3fc09e/tiny_obj_loader.h#L1541

You can print axes to debug whether it is working well or not.

**Comment by wsh2021** [comment] 2021-09-16 07:50
Hi @syoyo 

I did some tests and found some interesting results.

Test files:
- [ZH2.obj](https://github.com/wsh2021/FILE/blob/main/ZH2.obj)
- [ZH2.mtl](https://github.com/wsh2021/FILE/blob/main/ZH2.mtl)

First, I build a 3D to 2D rotate matrix(make sure the normal of result 2D shape is points out of the paper) for comparison with tinyobjloader 3D to 2D method, then plot these 2D points in matlab:

![image](https://user-images.githubusercontent.com/87893723/133561621-fc9756d6-efb8-4761-90a2-8fa0351cc5f8.png)

As you can see,  the left figure is CounterClockWise while the right one is ClockWise, so I suppose tinyobjloader's 2D conversion method is indeed wrong towards some shapes.

In addition, I also found that the output order of earcut(without holes) is always **CounterClockWise**, see below code:
```C++
#include <array>
#include <vector>
#include <iostream>
#include <earcut.hpp>

int main()
{
	// The number type to use for tessellation
	using Coord = double;

	// The index type. Defaults to uint32_t, but you can also pass uint16_t if you know that your
	// data won't have more than 65536 vertices.
	using N = uint32_t;

	// Create array
	using Point = std::array<Coord, 2>;
	std::vector<std::vector<Point>> polygon_ccw;
	std::vector<std::vector<Point>> polygon_cw;
	std::vector<std::vector<Point>> polygon_tol;

	// Fill polygon structure with actual data. Any winding order works.
	// The first polyline defines the main polygon.
	polygon_ccw.push_back({ {100, 0}, {100, 50}, {50, 50}, {50, 100}, {0, 100}, {0, 0} });
	polygon_cw.push_back({ {100, 0}, {0, 0}, {0, 100}, {50, 100}, {50, 50}, {100, 50} });
	polygon_tol.push_back({ {0, 0}, {0, 100}, {50, 50}, {50, 100}, {100, 100}, {100, 0} });


	// Run tessellation
	// Three subsequent indices form a triangle. Output triangles are clockwise???????
	std::vector<N> indices_ccw = mapbox::earcut<N>(polygon_ccw);
	std::vector<N> indices_cw = mapbox::earcut<N>(polygon_cw);
	std::vector<N> indices_tol = mapbox::earcut<N>(polygon_tol);

	// 4----3
	// |    |
	// |    2----1
	// |         |
	// |         |
	// 5---------0
	std::cout << "CounterClockWise: ";
	for (const auto& idx : indices_ccw) { std::cout << idx << "  "; }
	
	// 2----3
	// |    |
	// |    4----5
	// |         |
	// |         |
	// 1---------0
	std::cout << "\nClockWise: ";
	for (const auto& idx : indices_cw) { std::cout << idx << "  "; }

	//      3----4
	//      |    |
	// 1----2    |
	// |         |
	// |         |
	// 0---------5
	std::cout << "\nTinyObjLoader: ";
	for (const auto& idx : indices_tol) { std::cout << idx << "  "; }
}
```
The output:
```
CounterClockWise: 5  0  1  2  3  4  5  1  2  2  4  5
ClockWise: 1  0  5  4  3  2  1  5  4  4  2  1
TinyObjLoader: 5  4  3  2  1  0  5  3  2  2  0  5
```
Now, If we use triangle vertex indices of "TinyObjLoader" result, draw triangle on the "CounterClockWise" shape, the triangle winding order is ClockWise, this should be the reason for face inversion.

**Comment by syoyo** [comment] 2021-09-16 08:36
@wsh2021 Awesome! So we'll need to reorder indices by checking up face orientation of input triangle when 3D -> 2D conversion.

To do that, summing the cross product of each triangle of the polygon and seeing its sign will be suffice, as done in Earcut's implementation:

https://github.com/mapbox/earcut.hpp/blob/master/include/mapbox/earcut.hpp#L190

**Comment by wsh2021** [comment] 2021-09-16 09:05
Waiting for your good news 👍

**Comment by syoyo** [comment] 2021-09-16 12:29
> To do that, summing the cross product of each triangle of the polygon and seeing its sign will be suffice, as done in Earcut's implementation:

Oh, this wasn't suffice. We also need to consider input triangle is convex or concave: https://en.wikipedia.org/wiki/Curve_orientation

BTW: For .obj, vertex coordinate is right-handed, face orientation uses counter-clockwise order > https://en.wikipedia.org/wiki/Wavefront_.obj_file

**Comment by syoyo** [comment] 2021-09-18 19:37
@wsh2021 Ok, so after some investigation, the issue was Mapbox Earcut always reorder points in clockwise order(it ignores the face orientation of input polygon). So we need to flip the order of triangle indices of triangulated mesh by checking the orientation of input polygon and triangulated one(convex or concave wasn't a source of the issue)

Possible fix is now this PR: https://github.com/tinyobjloader/tinyobjloader/tree/mapboxearcut-correct-facing

@wsh2021 Could you please test more dataset you have? At least I've confirmed triangulation of ZH2-big works well.


![zh2-big-triangulated](https://user-images.githubusercontent.com/18676/133906591-1162294f-a522-48d7-aed0-295c953be223.png)

**Comment by wsh2021** [comment] 2021-09-29 04:06
@syoyo 

Sorry to reply so late. I just saw the message :)

I have tested my data and most of the faces are correct, but I still found three wrong faces, see that [ZH2_three_face.obj](https://github.com/wsh2021/FILE/blob/main/ZH2_three_face.obj).

Among these three faces, one may be because of the existence of common points, one may be because of the existence of collinearity, and the other I don't know why.

**Comment by syoyo** [comment] 2021-09-29 18:39
@wsh2021 Oh, there was a mistake to compute signed area.

Please use recent PR branch https://github.com/tinyobjloader/tinyobjloader/tree/mapboxearcut-correct-facing 

it fixes signed area computation and I've got correct result for `ZH2_three_face.obj`

<img width="671" alt="zh2-three-tri" src="https://user-images.githubusercontent.com/18676/135327984-80a00ccf-4e45-4ae6-88c8-8bd2937988c3.png">

**Comment by wsh2021** [comment] 2021-10-08 07:50
@syoyo 

Sorry to reply so late :)

Anyway, I have tested my data and the normal of the faces are all correct, but I found some face missing in the result , see that [ZH3_one_face.obj](https://github.com/wsh2021/FILE/blob/main/ZH3_one_face.obj).

**Comment by wsh2021** [comment] 2021-12-23 03:21
@syoyo 
I'm sorry I haven't contact you for quite a while,  too busy recently...

In order to convert 3D points into 2D, we can left multiply 3D point vector by a rotation matrix.
The function to get this rotation matrix:
```c++
inline Eigen::Matrix3d Get3DTo2DRotMat(
	const Eigen::Vector3d& pnormal,
	const Eigen::Vector3d& center,
	const Eigen::Vector3d& axis)
{
	Eigen::Vector3d row0 = (axis - center).normalized();
	Eigen::Vector3d row1 = (pnormal).cross(row0).normalized();
	Eigen::Vector3d row2 = pnormal.normalized();
	
	Eigen::Matrix3d R;
	R.row(0) = row0;
	R.row(1) = row1;
	R.row(2) = row2;
	
	return R;
}
```

*pnormal* is the face/plane normal
*center* is one vertex
*axis* is another vertex

Use this function:
```c++
// Assume that points of each face are coplanar
for (const auto& f_h : mesh.faces())
{
	CFVI fv_it = mesh.fv_range(f_h).begin();
	Vec3d cent = mesh.point(*fv_it);
	Vec3d axis = mesh.point(*(++fv_it));
	
	// Ensure cent and axis not the same point
	while (GetDistance(cent, axis) < 1e-4) 
	{
		axis = mesh.point(*(++fv_it));
	}
	
	Vec3d normal = mesh.normal(f_h);
	
	Mat3d R = Get3DTo2DRotMat(normal, cent, axis);

	for (const auto& v_h : mesh.fv_range(f_h))
	{
		Vec3d pt_3d = mesh.point(v_h);
		Vec2d pt_2d = (R * pt_3d).topRows(2);
	}
}
```

**Comment by syoyo** [comment] 2021-12-23 17:26
@wsh2021 Thanks!

```
Vec3d normal = mesh.normal(f_h);
```

How you calculate the normal for (concave and convex) polygon?

**Comment by wsh2021** [comment] 2021-12-24 12:30
@syoyo 

Use the Newell's Method, here are some related links:
[opengl-wiki](https://www.khronos.org/opengl/wiki/Calculating_a_Surface_Normal#Newell.27s_Method)
[stackoverflow](https://stackoverflow.com/a/8982812)

And this is the simple implementation refer to [openmesh](https://gitlab.vci.rwth-aachen.de:9000/OpenMesh/OpenMesh)
```c++
// Get face normal 
template <typename Point>
Vec3d GetFaceNormal(const std::vector<Point>& points_3d)
{
	// use Newell's Method to compute the surface normal
	Vec3d n(0, 0, 0);
	for (size_t i = 0; i < points_3d.size(); ++i)
	{
		size_t j = (i + 1) % points_3d.size();

		// http://www.opengl.org/wiki/Calculating_a_Surface_Normal
		const auto& a = points_3d[i] - points_3d[j];
		const auto& b = points_3d[i] + points_3d[j];

		n[0] += (a[1] * b[2]);
		n[1] += (a[2] * b[0]);
		n[2] += (a[0] * b[1]);
	}

	n.normalize();

	return n;
}
```

**Comment by syoyo** [comment] 2021-12-24 18:51
@wsh2021 Great! Thanks! I'll implement it into tinyobjloader and test if it goes well.

**Comment by tylermorganwall** [comment] 2022-10-01 21:04
I have created a pull request that I believe fixes this issue. It uses Newell's method to project the points to the coordinate system defined by the normal and triangulate there.

**Comment by syoyo** [comment] 2022-10-02 10:45
@tylermorganwall Thanks! the PR is here: https://github.com/tinyobjloader/tinyobjloader/pull/340

@wongshek Please try this branch https://github.com/tinyobjloader/tinyobjloader/tree/tylermorganwall-triangulation-fix (I've added some compilation fix over https://github.com/tinyobjloader/tinyobjloader/pull/340 ) solves triangulating your models. Apparently [ZH3_one_face.obj](https://github.com/wsh2021/FILE/blob/main/ZH3_one_face.obj) now tessellated correctly.

![Screenshot from 2022-10-02 19-38-42](https://user-images.githubusercontent.com/18676/193450104-4bc7a07c-ca1d-4f6d-b33c-b2274a044d2b.png)

**Comment by syoyo** [comment] 2022-10-09 12:34
PR #340 has been merged. So the issue should be solved in the recent `release` version of tinyobjloader.

@wongshek If you still encounter the issue, please reopen the issue.

**Closed by syoyo** 2022-10-09 12:34 UTC
Labels: bug

**Comment by tylermorganwall** [comment] 2022-10-21 01:25
My original pull request had a bug introduced when switching to a struct instead of an array (x-axis selected instead of y while calculating Newell's method), so I submitted another pull request to fix that bug.

**Comment by syoyo** [comment] 2022-10-21 08:35
@tylermorganwall Thsnk! https://github.com/tinyobjloader/tinyobjloader/pull/346

With that fix, I've confirmed regression tests(e.g. https://github.com/tinyobjloader/tinyobjloader/blob/release/models/issue-319-002.obj )  still process triangulation correctly.

**Comment by cedarz** [comment] 2023-01-15 04:05
@syoyo  I meet the same question when using the latest `release` branch.  When setting the CullMode to back, some submeshes can't be rendered, while CullMode as none gets nothing wrong. So I think it must be the reversing of face orientation after triangulation.
test obj file is from [here](https://free3d.com/zh/3d-model/old-lantern-pbr-98203.html)

**Comment by syoyo** [comment] 2023-01-15 08:14
@cedarz You should post minimal reproducible .obj with screenshots to illustrate the issue.

**Comment by cedarz** [comment] 2023-01-16 03:38
@syoyo  Feel sorry.  I used fbxsdk to load the FBX version with trigulation, but get the same result.  There may be something wrong with my coding. I should make it clear first, then post my results and test case here.
